# This configures Promtail's own internal
# HTTP server. This server is primarily used for exposing metrics (in
# Prometheus format, e.g., for Promtail's own health and performance monitoring)
# and for debugging purposes (e.g., checking its status). It's not typically
# used for ingesting logs from other sources.
server:
  http_listen_port: 9080
  grpc_listen_port: 0

# Promtail uses a "positions file" to
# keep track of how much of each log file it has already processed.
positions:
  filename: /tmp/positions.yaml

# The Loki instance(s) that Promtail will send logs to.
clients:
  - url: http://localhost:3100/loki/api/v1/push

# Defines what logs to scrape and send to loki and how
scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          # Specifies that the log files are located on the machine where Promtail is running
          - localhost
        labels:
          # Adds a label job="habit-market" to all logs. This is useful for filtering in Grafana.
          job: habit-market
          __path__: ${PROMTAIL_LOG_PATH:-./logs/server.log*}
    pipeline_stages:
      # In Loki, the most efficient and fundamental way to filter and query your logs is by labels.
      # We define labels here for some of the extracted fields.
      # The extracted fields are still useful if not a label in the case where you want to
      # make it a column in grafana
      - json:
          expressions:
            # These are the fields extracted from the JSON.
            timestamp: timestamp
            level: level
            message: message
            request_id: request_id
            method: method
            uri: uri
            status: status
            duration: duration
            error: error
      - labels:
        # Labels (easy filtering like: "{job="habit-market", level="error"} | json will quickly get you all error logs from habit-market.")
          level:
          method:
          status:
      - timestamp:
          source: timestamp
          format: RFC3339
