ALTER TABLE tasks
ADD COLUMN pinned BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE habits
ADD COLUMN pinned BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE rewards
ADD COLUMN pinned BOOLEAN NOT NULL DEFAULT FALSE;
