ALTER TABLE tasks
ADD COLUMN hidden BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE habits
ADD COLUMN hidden BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE rewards
ADD COLUMN hidden BOOLEAN NOT NULL DEFAULT FALSE;
