ALTER TABLE users
ADD COLUMN premium BOOL DEFAULT FALSE,
ALTER COLUMN premium SET NOT NULL;

CREATE TABLE IF NOT EXISTS api_keys (
    id CHAR(36) PRIMARY KEY,
    user_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
