version: 2.1

jobs:
  ci:
    docker:
      - image: cimg/base:2025.10
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install & Configure Nix
          command: |
            sh <(curl -L https://nixos.org/nix/install) --no-daemon
            mkdir -p ~/.config/nix
            echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf
            echo 'export USER=${USER:-circleci}' >> $BASH_ENV
            echo '. $HOME/.nix-profile/etc/profile.d/nix.sh' >> $BASH_ENV
      - run:
          name: Format Check
          command: |
            export USER=${USER:-circleci}
            . /home/circleci/.nix-profile/etc/profile.d/nix.sh
            nix develop --command cargo fmt --all --check
      - run:
          name: Lint Check
          command: |
            export USER=${USER:-circleci}
            . /home/circleci/.nix-profile/etc/profile.d/nix.sh
            nix develop --command cargo check
      - run:
          name: Start Services
          command: |
            export USER=${USER:-circleci}
            . /home/circleci/.nix-profile/etc/profile.d/nix.sh
            nix develop --command start
      - run:
          name: Run Migrations
          command: |
            export USER=${USER:-circleci}
            . /home/circleci/.nix-profile/etc/profile.d/nix.sh
            nix develop --command fw test_habit_market migrate
      - run:
          name: Run Tests
          command: |
            export USER=${USER:-circleci}
            . /home/circleci/.nix-profile/etc/profile.d/nix.sh
            nix develop --command t
      - run:
          name: Build Image
          command: |
            export USER=${USER:-circleci}
            . /home/circleci/.nix-profile/etc/profile.d/nix.sh
            nix develop --command nix build .#server-docker

      - persist_to_workspace:
          root: .
          paths:
            - result

  cd:
    docker:
      - image: cimg/base:2025.10
    resource_class: medium
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Build Image
          command: |
            docker load --input /tmp/result

            IMAGE_NAME="habit-market-backend" 
            ECR_REPOSITORY_URI="${{ steps.get-repository-uri.outputs.ECR_URI }}"
            IMAGE_TAG="latest"
            VERSION_TAG="${GITHUB_SHA::7}"
            docker tag ${IMAGE_NAME} "${ECR_REPOSITORY_URI}:${IMAGE_TAG}"
            docker tag ${IMAGE_NAME} "${ECR_REPOSITORY_URI}:${VERSION_TAG}"

            ECR_REPOSITORY_URI="${{ steps.get-repository-uri.outputs.ECR_URI }}"
            IMAGE_TAG="latest"
            VERSION_TAG="${GITHUB_SHA::7}"
            docker push "${ECR_REPOSITORY_URI}:${IMAGE_TAG}"
            docker push "${ECR_REPOSITORY_URI}:${IMAGE_TAG}"

workflows:
  ci:
    jobs:
      - test:
          filters:
            branches:
              only: main
      # - build:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: main
      # - migrate:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: main
