[package]
name = "habit-market-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = { version = "0.5.3", features = ["password-hash"] }
async-graphql = { version = "7.0.11", features = ["chrono"] }
async-graphql-axum = "7.0.11"
axum = { version = "0.7.7", features = ["macros"] }
axum-extra = { version = "0.9.4" }
chrono = "0.4.38"
rand = "0.8.5"
regex = "1.11.1"
serde = { version = "1.0.214", features = ["derive"] }
sqlx = { version = "0.8.2", features = ["chrono", "runtime-tokio", "postgres"] }
tokio = { version = "1.41.1", features = ["full"] }
uuid = { version = "1.11.0", features = ["v4"] }
