name: "CI"
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "migrations/**"
      - ".github/workflows/ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      echo "HI"
